### ISSUE TITLE
Collaboration proposal

### ISSUE THREAD

**Issue by jheredianet** [tero-jarvinen/teslamate-speed-temperature#3]
Hi @tero-jarvinen, first of all, congratulations on the great job. I really liked the idea of ​​this dashboard.

This is not an issue but rather a proposal. Would you like to participate in my repository where I have several custom dashboards for TeslaMate and share yours? In fact, I think you know it because I've seen that you've used part of the formulas that I've used for calculations on the Battery Health dashboard.

If you're interested, the only thing you need to do is make a pull request as explained [here](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards?tab=readme-ov-file#contributing).

For my part, I would commit to improving the dashboard, especially having only one that automatically recognizes the user's preferred units (so as not to have two dashboards per unit since it is more difficult to maintain), it is laborious at first, but not impossible.

On the other hand, there is an improvement to be made in the queries because they are quite slow, there are things that can be improved by making subqueries and working with indexes. I think that between the two of us we can improve it a lot.

I hope we can collaborate together for the benefit of Teslamate users. Thanks

**Comment by jheredianet** [comment]
Thank you @stauffenberg2020 for pointing me out this dashboard. It's really nice and interesting.

**Comment by tero-jarvinen** [comment]
Hi. I think your proposal is ok if you would like to improve the dashboard. My initial intention was to create one dashboard for different units but notised that it was not that simple to do and wasn't motivated enough to continue solving the problem.

I will create the pull request after I have done few small changes to the dashboard.

**Comment by jheredianet** [comment]
> Hi. I think your proposal is ok if you would like to improve the dashboard. My initial intention was to create one dashboard for different units but notised that it was not that simple to do and wasn't motivated enough to continue solving the problem.
> 
> I will create the pull request after I have done few small changes to the dashboard.

Thank you!
